apiVersion: v1
kind: Service
metadata:
  name: frext-socket-svc
spec:
  selector:
    app: frext-socket
  type: NodePort
  ports:
    - protocol: TCP
      port: 8040
      targetPort: 8040
      nodePort: 30040

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-socket
  labels:
    app: frext-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-socket
  template:
    metadata:
      labels:
        app: frext-socket
    spec:
      serviceAccountName:
        frext
      containers:
      - name: frext-socket
        image: wxwd14388/socket-test:v0.1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8040